export default {
  welcome: 'Welcome',
  logIn: 'Log In',
  createAccount: 'Sign Up',
  feed: 'feed',
  search: 'search',
  notification: 'notification',
  profile: 'profile',
  me: 'me',
  photo: 'photo',
  likes: 'likes',
  comments: 'comments',
  upload: 'upload',
  takePhoto: 'Take',
  selectPhoto: 'Select',
  rooms: 'Rooms',
  room: 'Room',
};
